# Jekyll configuration
TZ: Europe/Paris
permalink: /:year/:month/:day/:categories/:title.html
exclude: ['posts']
include: ['css']
safe: true

gems:
  - bootstrap-sass
  - jekyll-multiple-languages-plugin

# custom vars
name: Polyptyque
description: notes du projet Polyptyque
authors: Bertrand Sandrez, Arthur Violy
